name: Budowanie obrazu  

on:
  workflow_dispatch:
  push:


jobs:
  build:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v6
      
      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.actor }}/pawcho_zad2
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short  

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v4

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v4

        name: docker driver builder for cve testing
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker
          use: false
          name: localbuilder

      - 
        name: Login to ghcr
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - 
        name: SSH setup
        uses: MrSquaare/ssh-setup-action@v4
        with:
          host: github.com
          private-key: ${{ secrets.GH_SSHKEY }}

      - 
        name: Build image without pushing for testing
        uses: docker/build-push-action@v7
        with:
          builder: localbuilder
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.actor }}/pawcho_zad2_cache  
          cache-to: |
            type=registry,mode=max,ref=ghcr.io/${{ github.actor }}/pawcho_zad2_cache:${{github.sha}}
          ssh: default
          outputs: type=image,name=pawcho_zad2:test

      -   name: ls for testing
          run: docker image ls

      - 
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'pawcho_zad2:test'
          exit-code: '1'
          #ignore-unfixed: true
          cache: 'false'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - 
        name: Build and push the tested image again (from internal cache)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          ssh: default

      